const crypto = require('crypto');
const db = require('./db/database');
const JWT_SECRET = process.env.JWT_SECRET || 'change-this-secret-in-production';
function id() { return crypto.randomUUID(); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.pbkdf2Sync(password, salt, 120000, 32, 'sha256').toString('hex')}`; }
function verifyPassword(password, stored) { const [salt, expected] = String(stored).split(':'); if (!salt || !expected) return false; const actual = crypto.pbkdf2Sync(password, salt, 120000, 32, 'sha256').toString('hex'); return crypto.timingSafeEqual(Buffer.from(actual), Buffer.from(expected)); }
function base64url(value) { return Buffer.from(value).toString('base64url'); }
function signUser(user) { const header = base64url(JSON.stringify({alg:'HS256',typ:'JWT'})); const payload = base64url(JSON.stringify({sub:user.id,username:user.username,exp:Math.floor(Date.now()/1000)+7*86400})); const signature = crypto.createHmac('sha256', JWT_SECRET).update(`${header}.${payload}`).digest('base64url'); return `${header}.${payload}.${signature}`; }
function userFromToken(token) { const [header,payload,sig] = String(token||'').split('.'); if(!header||!payload||!sig) throw new Error('Invalid token.'); const expected=crypto.createHmac('sha256',JWT_SECRET).update(`${header}.${payload}`).digest('base64url'); if(sig.length!==expected.length || !crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))) throw new Error('Invalid token.'); const body=JSON.parse(Buffer.from(payload,'base64url').toString()); if(!body.exp || body.exp < Math.floor(Date.now()/1000)) throw new Error('Token expired.'); const user=db.users.find(u=>u.id===body.sub); if(!user) throw new Error('User no longer exists.'); return {id:user.id,username:user.username}; }
function register(username,password) { const name=String(username||'').trim().replace(/\s+/g,' ').slice(0,32); if(!name||typeof password!=='string'||password.length<6) throw new Error('Username is required and password must be at least 6 characters.'); if(db.users.some(u=>u.username.toLowerCase()===name.toLowerCase())) throw new Error('Username is already registered.'); const user={id:id(),username:name,password_hash:hashPassword(password),created_at:Date.now()}; db.users.push(user); db.save(); return {user:{id:user.id,username:user.username},token:signUser(user)}; }
function login(username,password) { const user=db.users.find(u=>u.username.toLowerCase()===String(username||'').trim().toLowerCase()); if(!user||!verifyPassword(String(password||''),user.password_hash)) throw new Error('Invalid username or password.'); return {user:{id:user.id,username:user.username},token:signUser(user)}; }
module.exports={register,login,userFromToken};
